spring:
  profiles:
    active: local
    group:
      local: local_server, common, secret

---
spring:
  config:
    activate:
      on-profile: common
  mybatis:
    mapper-locations: classpath*:mappers/**/*.xml
    type-aliases-package: com.Happy100BE.**.domain
    configuration:
      map-underscore-to-camel-case: true
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

logging:
  level:
    com.Happy100BE.Happy100: DEBUG
    org.springframework.security: INFO

---
spring:
  config:
    activate:
      on-profile: local_server
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/Happy100?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: secret
jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER:happy100-auth}
  access-token-validity-seconds: ${JWT_ACCESS_TOKEN_VALIDITY_SECONDS:3600}