spring:
  profiles:
    active: local
    group:
      local: local_server, common, secret

---

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Happy100?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver
    profiles:
      include: secret

mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: com.Happy100BE.**.domain
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

logging:
  level:
    com.Happy100BE.Happy100: DEBUG
    org.springframework.security: INFO

